"""
FastAPI web API for the ISACA SD career advisor agent.

Endpoints:
  GET  /api/health   — health check, no auth required
  POST /api/chat     — send a message, get a reply (requires Azure AD B2C JWT)

Authentication:
  Azure AD B2C issues JWTs after members sign in.
  Pass the token as:  Authorization: Bearer <token>

Session history:
  Conversation history is kept in memory per session_id.
  The session_id is a UUID generated by the chat widget on first load.
"""

import logging
from typing import Any

import httpx
from fastapi import FastAPI, HTTPException, Request, Security, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from jose import JWTError, jwt
from pydantic import BaseModel
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address

from agents.isaca_sd_agent import create_isaca_sd_agent
from config.settings import configure_logging, settings

configure_logging()
logger = logging.getLogger("api")


def _get_user_id(request: Request) -> str:
    """Rate-limit key: JWT sub claim if authenticated, otherwise client IP."""
    # JWT sub is stored in request.state by verify_token after successful auth.
    # Falls back to IP for unauthenticated paths (e.g. /api/health).
    return getattr(request.state, "user_sub", None) or get_remote_address(request)


limiter = Limiter(key_func=_get_user_id)

app = FastAPI(title="ISACA SD Advisor API", docs_url=None, redoc_url=None)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# ── CORS ────────────────────────────────────────────────────────────────────
# Only the ISACA SD website and localhost (for local testing) are allowed.

ALLOWED_ORIGINS = [
    "https://www.isaca-sd.org",
    "https://isaca-sd.org",
    "http://localhost",
    "http://localhost:3000",
    "http://localhost:8080",
    "http://127.0.0.1",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_methods=["GET", "POST"],
    allow_headers=["Authorization", "Content-Type"],
)

# ── JWT validation ───────────────────────────────────────────────────────────

security = HTTPBearer()
_jwks_cache: dict[str, Any] | None = None


def _jwks_url() -> str:
    tenant = settings.b2c_tenant_name
    policy = settings.b2c_policy_name
    return (
        f"https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com"
        f"/{policy}/discovery/v2.0/keys"
    )


async def _get_jwks() -> dict[str, Any]:
    global _jwks_cache
    if _jwks_cache is None:
        async with httpx.AsyncClient() as client:
            resp = await client.get(_jwks_url())
            resp.raise_for_status()
            _jwks_cache = resp.json()
    return _jwks_cache


async def verify_token(
    request: Request,
    credentials: HTTPAuthorizationCredentials = Security(security),
) -> dict:
    """Validate Azure AD B2C JWT. Returns decoded token claims on success."""
    token = credentials.credentials
    try:
        jwks = await _get_jwks()
        claims = jwt.decode(
            token,
            jwks,
            algorithms=["RS256"],
            audience=settings.b2c_client_id,
            options={"verify_aud": True, "verify_exp": True},
        )
        # Store sub in request.state so the rate limiter can key on it
        request.state.user_sub = claims.get("sub", "")
        return claims
    except JWTError as exc:
        logger.warning("JWT validation failed: %s", exc)
        # If the key was rotated, clear the cache and try once more
        global _jwks_cache
        if _jwks_cache is not None:
            _jwks_cache = None
            try:
                jwks = await _get_jwks()
                claims = jwt.decode(
                    token,
                    jwks,
                    algorithms=["RS256"],
                    audience=settings.b2c_client_id,
                    options={"verify_aud": True, "verify_exp": True},
                )
                return claims
            except JWTError:
                pass
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired token. Please sign in again.",
            headers={"WWW-Authenticate": "Bearer"},
        )





# ── Agent & session store ────────────────────────────────────────────────────

_agent = None  # lazy-initialized on first request


def _get_agent():
    global _agent
    if _agent is None:
        _agent = create_isaca_sd_agent()
    return _agent


# session_id → list of {"role": "user"|"assistant", "content": str}
_sessions: dict[str, list[dict]] = {}
_MAX_HISTORY = 6  # last 3 exchanges (6 messages total)


def _build_prompt(session_id: str, user_message: str) -> str:
    history = _sessions.get(session_id, [])
    if history:
        history_text = "\n".join(
            f"{'User' if m['role'] == 'user' else 'Advisor'}: {m['content']}"
            for m in history[-_MAX_HISTORY:]
        )
        return (
            f"[Previous conversation]\n{history_text}\n\n"
            f"[New message]\nUser: {user_message}"
        )
    return user_message


def _store_turn(session_id: str, user_message: str, reply: str) -> None:
    if session_id not in _sessions:
        _sessions[session_id] = []
    _sessions[session_id].append({"role": "user", "content": user_message})
    _sessions[session_id].append({"role": "assistant", "content": reply})


# ── Request / response models ────────────────────────────────────────────────


class ChatRequest(BaseModel):
    session_id: str
    message: str


class ChatResponse(BaseModel):
    reply: str
    session_id: str


# ── Endpoints ────────────────────────────────────────────────────────────────


@app.get("/api/health")
async def health() -> dict:
    return {"status": "ok", "model": settings.model}


@app.post("/api/chat", response_model=ChatResponse)
@limiter.limit("20/hour")
async def chat(
    request: Request,
    body: ChatRequest,
    claims: dict = Security(verify_token),
) -> ChatResponse:
    if not body.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty.")

    prompt = _build_prompt(body.session_id, body.message)

    try:
        result = await _get_agent().run(prompt)
        reply = result.text if hasattr(result, "text") else str(result)
    except Exception as exc:
        logger.error("Agent error for session %s: %s", body.session_id, exc, exc_info=True)
        raise HTTPException(status_code=500, detail="Something went wrong — please try again.")

    _store_turn(body.session_id, body.message, reply)
    return ChatResponse(reply=reply, session_id=body.session_id)
