"""
FastAPI web API for the ISACA SD career advisor.

Endpoints:
  GET  /             — chat UI (static HTML)
  GET  /api/health   — health check, no auth required
  POST /api/chat     — send a message, get a reply (requires auth)

Authentication (two modes — first one configured wins):
  1. Azure AD B2C JWT — set B2C_TENANT_NAME, B2C_CLIENT_ID in .env
     Pass token as: Authorization: Bearer <token>
  2. API key (beta/local) — set API_KEY in .env
     Pass key as: X-API-Key: <key>

If neither is configured, /api/chat rejects all requests with 401.

Session history:
  Conversation history is kept in memory per session_id.
  The session_id is a UUID generated by the chat widget on first load.
  Sessions are lost on API restart (use Phase C Redis to persist).
"""

import logging
from pathlib import Path
from typing import Any

import httpx
from fastapi import FastAPI, HTTPException, Request, Security, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.security import APIKeyHeader, HTTPAuthorizationCredentials, HTTPBearer
from fastapi.staticfiles import StaticFiles
from jose import JWTError, jwt
from pydantic import BaseModel
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address

from config.settings import configure_logging, settings
from isaca_sd.pipelines.isaca_sd_pipeline import ISACASdPipeline

configure_logging()
logger = logging.getLogger("api")

_STATIC_DIR = Path(__file__).parent / "static"


# ── Rate limiting ─────────────────────────────────────────────────────────────

def _get_user_id(request: Request) -> str:
    """Rate-limit key: authenticated user sub if available, otherwise client IP."""
    return getattr(request.state, "user_sub", None) or get_remote_address(request)


limiter = Limiter(key_func=_get_user_id)

app = FastAPI(title="ISACA SD Advisor API", docs_url=None, redoc_url=None)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# ── CORS ──────────────────────────────────────────────────────────────────────

ALLOWED_ORIGINS = [
    "https://www.isaca-sd.org",
    "https://isaca-sd.org",
    "http://localhost",
    "http://localhost:8000",
    "http://localhost:3000",
    "http://localhost:8080",
    "http://127.0.0.1",
    "http://127.0.0.1:8000",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_methods=["GET", "POST"],
    allow_headers=["Authorization", "Content-Type", "X-API-Key"],
)

# ── Auth — Azure AD B2C JWT ───────────────────────────────────────────────────

_bearer = HTTPBearer(auto_error=False)
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)
_jwks_cache: dict[str, Any] | None = None


def _jwks_url() -> str:
    tenant = settings.b2c_tenant_name
    policy = settings.b2c_policy_name
    return (
        f"https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com"
        f"/{policy}/discovery/v2.0/keys"
    )


async def _get_jwks() -> dict[str, Any]:
    global _jwks_cache
    if _jwks_cache is None:
        async with httpx.AsyncClient() as client:
            resp = await client.get(_jwks_url())
            resp.raise_for_status()
            _jwks_cache = resp.json()
    return _jwks_cache


async def _verify_jwt(
    request: Request,
    credentials: HTTPAuthorizationCredentials,
) -> dict:
    """Validate Azure AD B2C JWT. Returns decoded claims on success."""
    global _jwks_cache
    token = credentials.credentials
    for attempt in range(2):
        try:
            jwks = await _get_jwks()
            claims = jwt.decode(
                token,
                jwks,
                algorithms=["RS256"],
                audience=settings.b2c_client_id,
                options={"verify_aud": True, "verify_exp": True},
            )
            request.state.user_sub = claims.get("sub", "")
            return claims
        except JWTError as exc:
            if attempt == 0 and _jwks_cache is not None:
                # Keys may have rotated — clear cache and retry once
                _jwks_cache = None
                logger.warning("JWT validation failed, retrying with fresh JWKS: %s", exc)
                continue
            logger.warning("JWT validation failed: %s", exc)
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid or expired token. Please sign in again.",
                headers={"WWW-Authenticate": "Bearer"},
            )
    raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Authentication failed.")


async def verify_auth(
    request: Request,
    credentials: HTTPAuthorizationCredentials | None = Security(_bearer),
    api_key: str | None = Security(_api_key_header),
) -> dict:
    """
    Dual-mode auth dependency. Priority order:
      1. Azure AD B2C JWT (if B2C_CLIENT_ID is configured and Bearer token is present)
      2. API key (if API_KEY is configured and X-API-Key header is present)
    Returns decoded claims dict (at minimum {"sub": ...}).
    """
    # Mode 1 — Azure AD B2C JWT
    if settings.b2c_client_id and credentials:
        return await _verify_jwt(request, credentials)

    # Mode 2 — static API key (beta / local)
    if settings.api_key:
        if api_key and api_key == settings.api_key:
            request.state.user_sub = f"apikey:{api_key[:8]}"
            return {"sub": request.state.user_sub, "auth_method": "api_key"}
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid API key. Set X-API-Key header with the correct key.",
        )

    # Neither auth method is configured
    raise HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail=(
            "Authentication is not configured. "
            "Set B2C_CLIENT_ID (Azure AD B2C) or API_KEY in .env."
        ),
    )


# ── Pipeline & session store ──────────────────────────────────────────────────

_pipeline: ISACASdPipeline | None = None


def _get_pipeline() -> ISACASdPipeline:
    """Lazy-initialize the pipeline (creates all agents on first request)."""
    global _pipeline
    if _pipeline is None:
        logger.info("Initializing ISACASdPipeline...")
        _pipeline = ISACASdPipeline()
        logger.info("Pipeline ready.")
    return _pipeline


# session_id → list of {"role": "user"|"assistant", "content": str}
_sessions: dict[str, list[dict]] = {}
_MAX_HISTORY = 6  # keep last 3 exchanges (6 messages)


def _get_history(session_id: str) -> list[dict]:
    return _sessions.get(session_id, [])[-_MAX_HISTORY:]


def _store_turn(session_id: str, user_message: str, reply: str) -> None:
    if session_id not in _sessions:
        _sessions[session_id] = []
    _sessions[session_id].append({"role": "user", "content": user_message})
    _sessions[session_id].append({"role": "assistant", "content": reply})


# ── Request / response models ─────────────────────────────────────────────────


class ChatRequest(BaseModel):
    session_id: str
    message: str


class ChatResponse(BaseModel):
    reply: str
    session_id: str


# ── Endpoints ─────────────────────────────────────────────────────────────────


@app.get("/api/health")
async def health() -> dict:
    return {"status": "ok", "model": settings.model}


@app.post("/api/chat", response_model=ChatResponse)
@limiter.limit("20/hour")
async def chat(
    request: Request,
    body: ChatRequest,
    claims: dict = Security(verify_auth),
) -> ChatResponse:
    if not body.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty.")

    history = _get_history(body.session_id)

    try:
        reply = await _get_pipeline()._run_turn(body.message, history)
    except Exception as exc:
        logger.error("Pipeline error for session %s: %s", body.session_id, exc, exc_info=True)
        raise HTTPException(status_code=500, detail="Something went wrong — please try again.")

    _store_turn(body.session_id, body.message, reply)
    return ChatResponse(reply=reply, session_id=body.session_id)


# ── Static files (web chat UI) ────────────────────────────────────────────────
# Mount last so /api/* routes take priority.

if _STATIC_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(_STATIC_DIR)), name="static")

    @app.get("/")
    async def index() -> FileResponse:
        return FileResponse(str(_STATIC_DIR / "index.html"))
